### PR TITLE
Feature/autocomplete

### PR DESCRIPTION
**Pull request by fruitbat2000**
This PR seeks to resolve [MMMB-56](https://greenshootlabs.atlassian.net/browse/MMMB-56) by adding an Autocomplete message type. Key features:
- New Autocomplete component markup and styling
- Integration with an API endpoint provided in the message data to fetch an array of search results. Results are fetched upon keyup.
- Display of search results, including rendering the 'remainder' of the top search result in the input field.
- Addition of the perfect scrollbar component package for cross browser scrollbar styling on overflow elements
- Keyboard navigation of search results to complement click events
- Submission of selected term

### CODE REVIEW

**Comment by stu-greenshoots** [comment]
This @fruitbat2000 - As well as the comments around the attribute value needing to be added, I have a comment on the display. When the autocomplete opens with results, the message list needs to scroll to the bottom if possible. 

See this video:
https://drive.google.com/file/d/1sLCoVY7yyJfTQP4aovEyKl8VWsmAJSS0/view

Here, the text message that comes in before the autocomplete is relevant to the message so should stay in view.

I'm hoping we can use the scroll-down-message-list event in message list here:
https://github.com/opendialogai/webchat/blob/develop/resources/assets/js/components/MessageList.vue#L133

**Comment by fruitbat2000** [comment]
@stu-greenshoots - the attribute name should now be coming through:

image

As discussed, the designs don't actually include the preceding message when the input is expanded. There is some general work to be done regarding transitions between user input types, but I think this is best done when all the different message types are in place

**Comment by stu-greenshoots** [comment]
Thanks @fruitbat2000 - point taken on the preceding message.

For the value including the attribute name, I'm seeing the right value now, but the text also includes it :)
image

**Comment by fruitbat2000** [comment]
Doh!! Sorry, that should be fixed now!

**Pull request merged**
